@authToken=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImltcmFuLXphaG9vckBvdXRsb29rLmNvbSIsImlhdCI6MTYwMjQ4NTk5OSwiZXhwIjoxNjAyNDk1OTk5fQ.SDXSiDQJ9BX0ibGYdURuWRY038dLMxuqE2lkvp9GLpM
@baseUrl = http://localhost:3000/
###
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email":"imran-zahoor@outlook.com",
    "password":"admin1234"
}
###
GET {{baseUrl}}
Authorization: {{authToken}}

###
POST {{baseUrl}}/auth/logout
Content-Type: application/json
Authorization: {{authToken}}

{
    "email":"imran-zahoor@outlook.com",
    "password":"admin1234"
}

###
GET {{baseUrl}}/api/todo
Content-Type: application/json
Authorization: {{authToken}}
###
GET {{baseUrl}}/api/todo/5f8403ca9433e531d26ca747
Content-Type: application/json
Authorization: {{authToken}}

###
POST {{baseUrl}}/api/todo
Content-Type: application/json
Authorization: {{authToken}}

{
    "title":"deploy jenkins solution" 
}

###
PUT {{baseUrl}}/api/todo/5f8403ca9433e531d26ca747
Content-Type: application/json
Authorization: {{authToken}}

{
    "completed":true
}

###
DELETE  {{baseUrl}}/api/todo/5f8403ca9433e531d26ca747
Content-Type: application/json
Authorization: {{authToken}}